### create account
POST http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "initialBalance": 1234500
}

### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 20000
}

### use balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "d8e131d8724d4352b7563c2820c7d7b4",
  "accountNumber": "1000000002",
  "amount": 20000
}

### query transaction
GET http://localhost:8080/transaction/9bb82bb895da4b41be7b72c1cdc9be9c